Repository commaai/website, pull requests merged in 2025-03, with the labels that each got.

#46 Refactor harnesses to support only showing vehicle (or generic) harnesses, and include make
  src/lib/components/HarnessSelector/HarnessSelector.svelte
  src/lib/utils/harnesses.js
Labels: refactor

#35 generate harness parts list
  scripts/compatibility.py
  src/lib/non-standard-harness-parts.html
  src/lib/standard-harness-parts.html
  src/lib/utils/harnesses.js
  src/routes/shop/products/car-harness.svelte
  templates/harness-parts_template.html
  templates/non-standard-harness-parts_template.html
  templates/standard-harness-parts_template.html
  templates/vehicles_template.json
Labels: enhancement

#54 fix(harnesses): skip car model without harness
  src/lib/utils/harnesses.js
Labels: bugfix

#61 compatibility: get_all_car_docs once
  scripts/compatibility.py
Labels: refactor
